// <auto-generated />
using System;
using GestionVacaciones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionVacaciones.Data.Migrations
{
    [DbContext(typeof(VacacionesDbContext))]
    partial class VacacionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionVacaciones.Data.Entidades.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int?>("DesignadoId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("IX_Empleado_Correo");

                    b.HasIndex("DesignadoId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("GestionVacaciones.Data.Entidades.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasCorridos")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId", "FechaCreacion")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Solicitud_EmpleadoId_FechaCreacion");

                    b.ToTable("Solicitudes", t =>
                        {
                            t.HasCheckConstraint("CK_Solicitud_DiasCoincidenConPeriodo", "[DiasCorridos] = DATEDIFF(day, [FechaInicio], [FechaFin]) + 1");

                            t.HasCheckConstraint("CK_Solicitud_DiasPositivos", "[DiasCorridos] > 0");

                            t.HasCheckConstraint("CK_Solicitud_EstadoValido", "[Estado] BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_Solicitud_PeriodoCoherente", "[FechaFin] >= [FechaInicio]");
                        });
                });

            modelBuilder.Entity("GestionVacaciones.Data.Entidades.Empleado", b =>
                {
                    b.HasOne("GestionVacaciones.Data.Entidades.Empleado", "Designado")
                        .WithMany()
                        .HasForeignKey("DesignadoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestionVacaciones.Data.Entidades.Empleado", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Designado");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GestionVacaciones.Data.Entidades.Solicitud", b =>
                {
                    b.HasOne("GestionVacaciones.Data.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
